task: nerf
gpus: [0]
exp_name: 'img_fit'
scene: 'lego'

train_dataset_module: lib.datasets.img_fit.synthetic
test_dataset_module: lib.datasets.img_fit.synthetic
network_module: lib.networks.img_fit.network
loss_module: lib.train.losses.img_fit
evaluator_module: lib.evaluators.img_fit
visualizer_module: lib.visualizers.img_fit

task_arg:
    N_pixels: 8192
    chunk_size: 16384

network:
    W: 128
    D: 4
    uv_encoder:
        type: 'frequency'
        input_dim: 2
        freq: 10

train_dataset:
    data_root: 'data/nerf_synthetic'
    split: 'train'
    view: 0
    input_ratio: 1.

test_dataset:
    data_root: 'data/nerf_synthetic'
    view: 0
    split: 'test'
    input_ratio: 0.5

train:
    batch_size: 1
    lr: 5e-4
    weight_decay: 0.
    epoch: 20 # 100 * 500
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 20
    num_workers: 4

test:
    batch_size: 1

ep_iter: 500
eval_ep: 10       # 50 iterations
save_latest_ep: 20 # 10000 iterations
log_interval: 100
